#!/bin/bash
# XFCE DCV session with alternative window manager

# Set background
xsetroot -solid grey

# Disable thumbnail generation for faster file browser
export TUMBLER_DISABLE=1

# Use openbox as window manager (works in containers)
openbox &

# Wait for WM
sleep 1

# Start XFCE panel (with --disable-wm-check since we're using metacity)
xfce4-panel --disable-wm-check &

# Start desktop (with --disable-wm-check)
xfdesktop --disable-wm-check &

# Start terminal
xfce4-terminal --maximize &

# Keep session alive
wait
